### ISSUE TITLE
Strange connection closed by host

### ISSUE THREAD

**Issue by QustomQure** [6block/zkwork_ironminer#5] opened 2022-09-11 06:34 UTC
![2022-09-11_09-26-39](https://user-images.githubusercontent.com/43998465/189515417-63a2797a-348a-4326-a716-e861447586b8.png)

**Comment by hairtail** [comment] 2022-09-13 09:27
This is not a bug. Tcp connection is closed by server. We restarted our server in that time I guess.

**Closed as completed by hairtail** 2022-09-13 09:27 UTC
